# Build and publish a release of the project using semantic-release whenever
# changes are merged into main.
name: "Release"

on:
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - README.md
      - "docs/**"

env:
  IMAGE_NAME: ghcr.io/shadowblip/opengamepadui-builder

# Jobs to run
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install @semantic-release/exec @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make sem-release
